services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8000"
    env_file:
      - .env
    volumes:
      - data:/app/data
    restart: unless-stopped

volumes:
  data: